name: tutoring_budget
description: A new Flutter project.
publish_to: 'none'
version: 1.2.1+14

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3 # збереження та читання пареметрів
  intl: ^0.20.2
  auto_size_text: ^3.0.0  # зміна розміру тексту
  convex_bottom_bar: ^3.2.0 # прикольне нижнє меню
  flutter_slidable: ^4.0.3 # Слайдер
  uuid: ^4.5.2 # Генерація унікального id
  table_calendar: ^3.2.0 # календар
  flutter_email_sender: ^8.0.0
  store_redirect: ^2.0.4 # для оцінювання проекту
  share_plus: ^12.0.1  # для розшарення чогось

  line_icons: ^2.0.3              # іконки
  iconsax: ^0.0.8                 # іконки

  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_app_name:
  name: "Tutor budget"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans/SofiaSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/SofiaSans/SofiaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SofiaSans/SofiaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/SofiaSans/SofiaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SofiaSans/SofiaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SofiaSans/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaSans/SofiaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/SofiaSans/SofiaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SofiaSans/SofiaSans-Black.ttf
          weight: 900

        - asset: assets/fonts/SofiaSans/SofiaSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SofiaSans/SofiaSans-BlackItalic.ttf
          weight: 900
          style: italic
